name: test-resources
run-name: Testing keywords and thesaurus configuration files
on:
  push:
jobs:
  test-resources:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14' # or the version you are using

      - name: Install dependencies
        run: yarn install # or 'npm install' if you are using npm

      - name: Run tests
        run: yarn test # or the command you use to run your tests
